Repository tlambert03/napari-omero, pull requests merged in 2025-05, with the labels that each got.

#81 Support loading pyramids as multiscale layers
  README.md
  src/napari_omero/plugins/loaders.py
Labels: enhancement, high priority

#100 Add roi plugin
  README.md
  src/napari_omero/napari.yaml
  src/napari_omero/plugins/masks.py
  src/napari_omero/widgets/ROIs.py
  src/napari_omero/widgets/__init__.py
  tests/test_widget.py
Labels: enhancement

#109 prepend image id to layer
  src/napari_omero/plugins/loaders.py
Labels: enhancement

#111 Update pyproject.toml to not restrict vispy (drop it)
  pyproject.toml
Labels: maintenance
